"""Time and cost of every model run, from the run records. Writes out/costs.json and out/costs.md.

What is counted, and what isn't:
- One record = one drawing processed by one tool under one label. Trace labels (the code-only line tracer run on an
  earlier model answer) copy the source run's seconds and cost; they are counted only for the tracer's own seconds,
  never again for the model call.
- `seconds` is wall-clock. In tiled mode 4 tiles run in parallel, so serial compute (`tile_seconds_sum`) is also
  reported: that's the number to use for capacity planning on one worker.
- Gemini and Gemma dollars are ESTIMATES: the tokens Google reports, priced at the deliberately high rates in
  run_extraction.py (GEMINI_PRICE). Gemma is priced at the same rates, which overstates it. Not a bill.
- Claude dollars are NOTIONAL: the API-equivalent figure the Claude Code CLI reports. The runs used a flat
  subscription, so the marginal cost was $0. Codex (GPT) reports no cost at all; it also ran on a subscription.
- runs/gemini_spend.json is the running ledger the spend cap enforces; the total here must match it.

Run records live in runs/ (gitignored; they hold raw model output). This script is the bridge: out/costs.* is
committed so every cost number in the docs traces to a file.

Usage: python scripts/cost_report.py
"""
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "runs"
OUT = ROOT / "out"


def tool_name(rec):
    model = (rec.get("model") or "").lower()
    return "gemma" if "gemma" in model else rec["tool"]


def main():
    agg = defaultdict(lambda: {"records": 0, "calls": 0, "wall_s": 0.0, "serial_s": 0.0, "usd_est": 0.0,
                               "usd_notional": 0.0, "failed": 0})
    tracer = {"runs": 0, "seconds": 0.0, "max": 0.0, "min": None}
    for f in sorted(RUNS.glob("*/*/*.json")):
        rec = json.loads(f.read_text(encoding="utf-8"))
        if "tracer" in rec:  # trace labels: count the tracer only
            s = rec["tracer"].get("seconds") or 0.0
            tracer["runs"] += 1
            tracer["seconds"] += s
            tracer["max"] = max(tracer["max"], s)
            tracer["min"] = s if tracer["min"] is None else min(tracer["min"], s)
            continue
        if "source_label" in rec:
            continue
        label = f.parent.parent.name
        tiled = "tiling" in rec
        tool = tool_name(rec)
        kind = "smoke" if label.startswith("smoke") else ("tiled 2x2" if tiled else "whole sheet")
        for key in ((tool, kind), (tool, "all")):
            a = agg[key]
            a["records"] += 1
            a["calls"] += len(rec.get("tiles", [])) if tiled else 1
            a["calls"] += 1 if tiled and (rec["tiling"].get("overview") or {}).get("source") == "fresh whole-sheet call" else 0
            a["wall_s"] += rec.get("seconds") or 0.0
            a["serial_s"] += rec["tiling"]["tile_seconds_sum"] if tiled else (rec.get("seconds") or 0.0)
            a["usd_est"] += rec.get("cost_usd") or 0.0
            a["usd_notional"] += rec.get("cost_usd_notional") or 0.0
            a["failed"] += 1 if (rec.get("error") or rec.get("parse_error")) and not rec.get("prediction") else 0

    rows = []
    for (tool, kind), a in sorted(agg.items()):
        n = a["records"] or 1
        rows.append({"tool": tool, "mode": kind, "drawings": a["records"], "model_calls": a["calls"],
                     "failed_drawings": a["failed"], "wall_hours": round(a["wall_s"] / 3600, 2),
                     "mean_wall_s_per_drawing": round(a["wall_s"] / n, 1),
                     "mean_serial_s_per_drawing": round(a["serial_s"] / n, 1),
                     "usd_estimated": round(a["usd_est"], 3), "usd_estimated_per_drawing": round(a["usd_est"] / n, 4),
                     "usd_notional": round(a["usd_notional"], 2),
                     "usd_notional_per_drawing": round(a["usd_notional"] / n, 4)})
    ledger = json.loads((RUNS / "gemini_spend.json").read_text()) if (RUNS / "gemini_spend.json").exists() else {}
    est_total = round(sum(r["usd_estimated"] for r in rows if r["mode"] == "all"), 3)
    result = {"rows": rows, "tracer": {**tracer, "seconds": round(tracer["seconds"], 1),
                                       "mean_s": round(tracer["seconds"] / max(1, tracer["runs"]), 1)},
              "gemini_ledger_usd": ledger.get("usd"), "gemini_cap_usd": ledger.get("cap"),
              "estimated_total_usd": est_total,
              "ledger_matches_records": ledger.get("usd") is not None and abs(ledger["usd"] - est_total) < 0.01}
    OUT.mkdir(exist_ok=True)
    (OUT / "costs.json").write_text(json.dumps(result, indent=1), encoding="utf-8")

    lines = ["# Model time and cost, from the run records (generated by scripts/cost_report.py)", "",
             "Wall = elapsed time (tiles run 4 in parallel). Serial = summed call time, for capacity planning.",
             "Estimated $ = reported tokens at deliberately high list rates (not a bill). Notional $ = Claude Code's",
             "API-equivalent figure for subscription use. GPT via Codex records no cost (subscription).", "",
             "| Tool | Mode | Drawings | Calls | Failed | Wall h | Wall s/drawing | Serial s/drawing | "
             "Est. $/drawing | Notional $/drawing | Est. $ total | Notional $ total |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['tool']} | {r['mode']} | {r['drawings']} | {r['model_calls']} | {r['failed_drawings']} | "
                     f"{r['wall_hours']} | {r['mean_wall_s_per_drawing']} | {r['mean_serial_s_per_drawing']} | "
                     f"{r['usd_estimated_per_drawing'] or ''} | {r['usd_notional_per_drawing'] or ''} | "
                     f"{r['usd_estimated'] or ''} | {r['usd_notional'] or ''} |")
    t = result["tracer"]
    lines += ["", f"Line tracer (code, no model): {t['runs']} runs, {t['seconds']} s total, {t['min']}-{t['max']} s "
                  f"per drawing, mean {t['mean_s']} s.",
              f"Estimated model spend in the records: ${est_total}. Spend ledger (runs/gemini_spend.json): "
              f"${result['gemini_ledger_usd']} of a ${result['gemini_cap_usd']} cap. "
              f"{'They match.' if result['ledger_matches_records'] else 'MISMATCH: investigate.'}"]
    (OUT / "costs.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
