"""Normal operating bands for the Tennessee Eastman tags, learned from normal running, and an honest check of them.

What an operator gets: each value on the screens shows its normal band. A value outside it is flagged on the screen
(not alarmed), often well before any alarm. That is the first-pass inference this script makes and tests.

  Fit:      the first half of the normal run (d00 test file, samples 0-479): band = mean +/- K standard deviations.
  Check 1:  the second half of the normal run (480-959), which the fit never saw. How often is anything flagged when
            nothing is wrong? Every flag there is a false one.
  Check 2:  the fault-6 run (A feed loss, starts at sample 160). How long after the fault does the first flag appear,
            and how much warning is that before the reactor pressure alarm (PI-107 > 2895 kPa)?

K is chosen on Check 1 only (the smallest K whose false-flag rate per tag is under 0.5%), then Check 2 is reported for
that K. The fault run never chooses anything.

Model use: none. This is plain statistics on the published TE data. Claude (the coding agent) chose the method and
wrote the code; no model output is an input.

  python scripts/normal_bands.py            # writes out/ignition/normal_bands.json and .md
"""
import json
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts" / "ignition"))
DATA = ROOT / "data" / "external" / "te-braatz"
OUT = ROOT / "out" / "ignition"
FIT, FAULT_START, ALARM = 480, 160, ("PI-107", 2895.0)
KS = (3, 4, 5, 6)


def load(name):
    return [list(map(float, l.split())) for l in (DATA / name).read_text().splitlines() if l.strip()]


def main(quiet=False):
    from build_gateway import te_columns  # noqa: E402 (lazy: build_gateway imports this module too)
    model = json.loads((ROOT / "data" / "te_process_model.json").read_text(encoding="utf-8"))
    cols = te_columns(model)
    d00, d06 = load("d00_te.dat"), load("d06_te.dat")
    stats = {}
    for tag, c in cols.items():
        fit = [r[c] for r in d00[:FIT]]
        stats[tag] = (statistics.fmean(fit), statistics.pstdev(fit) or 1e-9)

    def flags(rows, k, tag):
        m, s = stats[tag]
        c = cols[tag]
        return [i for i, r in enumerate(rows) if abs(r[c] - m) > k * s]

    held = d00[FIT:]
    table = {}
    for k in KS:
        per_tag = {t: len(flags(held, k, t)) / len(held) for t in cols}
        any_rate = sum(1 for r in held if any(abs(r[cols[t]] - stats[t][0]) > k * stats[t][1] for t in cols)) / len(held)
        worst = max(per_tag, key=per_tag.get)
        table[k] = (per_tag[worst], statistics.fmean(per_tag.values()), any_rate, worst)
    k = next((k for k in KS if table[k][0] < 0.005), KS[-1])

    alarm_at = next(i for i, r in enumerate(d06) if r[cols[ALARM[0]]] > ALARM[1])
    first = {}
    for t in cols:
        f = [i for i in flags(d06, k, t) if i >= FAULT_START]
        if f:
            first[t] = f[0]
    order = sorted(first.items(), key=lambda x: x[1])
    false_before = sorted({t for t in cols for i in flags(d06[:FAULT_START], k, t)})

    bands = {t: {"mean": round(m, 4), "sd": round(s, 5), "lo": round(m - k * s, 4), "hi": round(m + k * s, 4)}
             for t, (m, s) in stats.items()}
    result = {"k": k, "fit": "d00_te samples 0-479", "check_normal": "d00_te samples 480-959",
              "false_flag_rate_by_k": {kk: {"worst_tag": round(v[0], 4), "mean_tag": round(v[1], 4),
                                             "any_tag": round(v[2], 4), "worst": v[3]} for kk, v in table.items()},
              "fault6": {"fault_start_sample": FAULT_START, "alarm_sample": alarm_at,
                         "first_flags": [{"tag": t, "sample": i, "minutes_after_fault": (i - FAULT_START) * 3}
                                         for t, i in order[:8]],
                         "flags_before_fault": false_before},
              "bands": bands}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "normal_bands.json").write_text(json.dumps(result, indent=1), encoding="utf-8")

    lead = (alarm_at - order[0][1]) * 3 if order else None
    md = ["# Normal operating bands: fit and check", "",
          "Generated by `scripts/normal_bands.py`. One TE sample is 3 minutes of plant time.", "",
          f"**Band:** mean ± {k} standard deviations, fitted on the first half of the normal run.", "",
          "| K | False flags, worst tag | Mean tag | Any of 37 tags flagged |", "|---|---|---|---|"]
    md += [f"| {kk} | {v[0]:.1%} ({v[3]}) | {v[1]:.2%} | {v[2]:.1%} |" for kk, v in table.items()]
    md += ["", f"K = {k} is the smallest with every tag under 0.5% false flags on the unseen half of the normal run.",
           "", "**Fault 6 (A feed loss)**, which the choice of K never saw:", "",
           f"- The fault starts at sample {FAULT_START}; the reactor pressure alarm (PI-107 > 2895 kPa) comes at "
           f"sample {alarm_at}, {(alarm_at - FAULT_START) * 3} minutes later.",
           f"- The first band flag comes at sample {order[0][1]} ({order[0][0]}), "
           f"{(order[0][1] - FAULT_START) * 3} minutes after the fault: **{lead} minutes of warning before the alarm**."
           if order else "- No flag after the fault.",
           f"- Flags before the fault (false): {', '.join(false_before) or 'none'}.", "",
           "| First flags after the fault | Sample | Minutes after fault |", "|---|---|---|"]
    md += [f"| {t} | {i} | {(i - FAULT_START) * 3} |" for t, i in order[:8]]
    (OUT / "normal_bands.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    if not quiet:
        print("\n".join(md))
    return result


if __name__ == "__main__":
    main()
